In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [18]:
scalar.shape

TensorShape([])

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [6]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

In [7]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [8]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [9]:
random_1 = tf.random.Generator.from_seed(30)
random_1 = random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ]], dtype=float32)>

In [10]:
tf.random.set_seed(42)
tf.random.shuffle(random_1, seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8357487 ,  0.20849545],
       [ 1.4040174 , -2.735283  ],
       [ 1.2232229 , -1.8653691 ]], dtype=float32)>

In [11]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.15012848], shape=(1,), dtype=float32)
tf.Tensor([0.11101711], shape=(1,), dtype=float32)


In [12]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.3665805], shape=(1,), dtype=float32)
tf.Tensor([0.4828781], shape=(1,), dtype=float32)


In [13]:
import numpy as np 
numpy_A =  np.arange(1,57, dtype=np.int32)
numpy_A

# X =  tf.constant(Some_Matrix)
# y = tf.constant(vectors)
A = tf.constant(numpy_A, shape = (4,7,2)) # Reshape la multiplicacion interna debe dar la cantidad de valores
B = tf.constant(numpy_A)
A,B


(<tf.Tensor: shape=(4, 7, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12],
         [13, 14]],
 
        [[15, 16],
         [17, 18],
         [19, 20],
         [21, 22],
         [23, 24],
         [25, 26],
         [27, 28]],
 
        [[29, 30],
         [31, 32],
         [33, 34],
         [35, 36],
         [37, 38],
         [39, 40],
         [41, 42]],
 
        [[43, 44],
         [45, 46],
         [47, 48],
         [49, 50],
         [51, 52],
         [53, 54],
         [55, 56]]], dtype=int32)>,
 <tf.Tensor: shape=(56,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56], dtype=int32)>)

In [14]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [15]:

#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

#Get the first from each dimension except for the final one
rank_4_tensor[:1,:,:1,:]

#Las item of each dimension
rank_4_tensor[:,-1]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [16]:
rank_2_tenor = tf.zeros([2,2])
rank_2_tenor.ndim, rank_2_tenor.shape , tf.size(rank_2_tenor).numpy()

(2, TensorShape([2, 2]), 4)

In [17]:
rank_4_tensor[:,-1]
Rank_5_tensor = rank_4_tensor[... , tf.newaxis]
Rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

In [30]:
tensor_1 = tf.random.uniform(shape=(5,300), minval = 0 , maxval=1 )
tensor_2 = tf.random.uniform(shape=(5,300), minval = 0 , maxval=1 )
tensor_2 = tf.transpose(tensor_2)

tensor_2
matrix_multiplication = tf.linalg.matmul(tensor_1, tensor_2)




<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[6.7427254e-01, 3.5018390e-01, 8.1061977e-01, ..., 4.3177831e-01,
        7.4501061e-01, 2.7054095e-01],
       [6.8262398e-01, 2.2428446e-01, 1.7597814e-07, ..., 9.5903182e-01,
        2.1629143e-04, 3.1328878e-01],
       [5.7757354e-01, 1.3745986e-01, 1.1447197e-01, ..., 3.9307994e-01,
        1.4650379e-01, 1.0502181e-01],
       [2.7559745e-01, 2.8441581e-01, 1.8237017e-03, ..., 7.6511358e-03,
        1.8212894e-03, 2.2496311e-03],
       [5.5628810e-03, 4.6216649e-01, 6.1339164e-01, ..., 6.9353962e-01,
        7.7014780e-03, 5.2944303e-01]], dtype=float32)>

In [41]:
tensor_3 = tf.random.uniform(shape=(224,224,3), minval = 0 , maxval=1)
tensor_3

Flat_tensor= tf.reshape( tensor_3, [-1])
tf.reducemaz(Flat_tensor)
tf.reducemin(Flat_tensor)

tensor_4 = tf.random.uniform(shape=(1,224,224,3), minval = 0 , maxval=1)
tf.squeeze(tensor_4)



<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.4347762 , 0.783973  , 0.01271129],
        [0.13626301, 0.6833308 , 0.47180676],
        [0.69921005, 0.07350874, 0.46142745],
        ...,
        [0.73583996, 0.94842637, 0.2061224 ],
        [0.67593133, 0.8937776 , 0.7957877 ],
        [0.61997914, 0.33385825, 0.86503994]],

       [[0.350034  , 0.73666346, 0.5707258 ],
        [0.5360997 , 0.2822925 , 0.3049438 ],
        [0.01953852, 0.28035772, 0.35258782],
        ...,
        [0.50166595, 0.48181129, 0.42483056],
        [0.05111408, 0.08426905, 0.49541712],
        [0.92492783, 0.3204112 , 0.8534446 ]],

       [[0.5244334 , 0.07796919, 0.44118345],
        [0.93896735, 0.09403789, 0.11194611],
        [0.7893889 , 0.01683712, 0.8270042 ],
        ...,
        [0.5227617 , 0.43359447, 0.13507414],
        [0.07826984, 0.37148237, 0.6905519 ],
        [0.16952515, 0.94142365, 0.8570434 ]],

       ...,

       [[0.9320873 , 0.07752156, 0.14031208],
        [0.82

In [65]:
tensor_5 = tf.constant([1.0, 2.0, 3.0,4.0,5.0,6.0,7.0,25.0,32.0,31.0])
tf.argmax(tensor_5)

tf.one_hot(tf.cast(tf.reshape(tensor_5, -1), dtype=tf.int32), depth=10)
                

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>